apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |-
    {
      "httpConfig": {
        "port": "{{ .Values.service.port }}"
      },
      "redisConfig": {
        "host": "{{ .Values.redis.host }}",
        "port": {{ .Values.redis.port }},
        "database": {{ .Values.redis.database }}
      },
      "postgresConfig": {
        "host": "{{ .Values.db.host }}",
        "port": {{ .Values.db.port }},
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}",
        "database": "{{ .Values.db.database }}"
      }
    }
