---
compressionLevel: "mixed"
enableGlobalCache: false
nodeLinker: "node-modules"
yarnPath: ".yarn/releases/yarn-4.2.2.cjs"
npmScopes:
  benslabbert:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${GH_TOKEN}"
