---
version: "2.4"
services:
  redis:
    healthcheck:
      test: "redis-cli ping"
      interval: "1s"
      timeout: "1s"
      retries: 10
    image: "redis/redis-stack:latest"
    ports:
    - "6379:6379"
    - "8001:8001"
    mem_limit: "512m"
  postgres:
    healthcheck:
      test: "pg_isready -U postgres"
      interval: "5s"
      timeout: "5s"
      retries: 10
    image: "postgres:15-alpine"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
    - "./create-all-databases.sql:/docker-entrypoint-initdb.d/create-all-databases.sql"
    mem_limit: "512m"
