---
services:
  catalog-migrator:
    image: "catalog-migration:jvm-latest"
    depends_on:
      postgres:
        condition: "service_healthy"
    command: "java -Xmx32M -Xms32M -Djava.net.preferIPv4Stack=true -XX:+UnlockExperimentalVMOptions\
      \ -XX:+UseEpsilonGC -jar app.jar postgres 5432 postgres postgres catalog"
    mem_limit: "256m"
  payment-migrator:
    image: "payment-migration:jvm-latest"
    depends_on:
      postgres:
        condition: "service_healthy"
    command: "java -Xmx32M -Xms32M -Djava.net.preferIPv4Stack=true -XX:+UnlockExperimentalVMOptions\
      \ -XX:+UseEpsilonGC -jar app.jar postgres 5432 postgres postgres payment"
    mem_limit: "256m"
