---
version: "2.4"
services:
  redis:
    image: "redis/redis-stack:latest"
    ports:
    - "6379:6379"
    - "8001:8001"
    mem_limit: "512m"
  postgres:
    image: "postgres:15-alpine"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
    - "./create-all-databases.sql:/docker-entrypoint-initdb.d/create-all-databases.sql"
    mem_limit: "512m"
